- name:
  apt_repository: 
    repo: 'ppa:ondrej/php' 
    state: present 
    update_cache: yes

- name: Instalar o pacote do PHP-FPM e a extensão do MySQL
  apt: 
    name: "{{ item }}" 
    state: latest 
  loop: [ 
    'php7.3-fpm', 
    'php7.3-mysql'
  ]